version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:    
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13            
      - run:
          name: Build Docker image
          command:
            docker build -t supportlik/carpool:$CIRCLE_BRANCH -t supportlik/carpool:latest -t supportlik/carpool:1.0.$CIRCLE_BUILD_NUM .
      - run:
          name: Publish Docker image
          command:
            docker push supportlik/carpool:$CIRCLE_BRANCH supportlik/carpool:latest supportlik/carpool:1.0.$CIRCLE_BUILD_NUM    