version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login Docker
          command:
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build Docker Image
          command:
            docker build -t supportlik/carpool:$CIRCLE_BRANCH -t supportlik/carpool:latest -t supportlik/carpool:1.0.$CIRCLE_BUILD_NUM .
      - run:
          name: Publish Docker Image Build Number
          command:
            docker push supportlik/carpool:1.0.$CIRCLE_BUILD_NUM
      - run:
          name: Publish Docker Image CircleBranch
          command:
            docker push supportlik/carpool:$CIRCLE_BRANCH
      - run:
          name: Publish Docker Image Latest
          command:
            docker push supportlik/carpool:latest